services:
  - type: web
    name: sigma-chat-flask
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 3 -k gthread -b 0.0.0.0:$PORT wsgi:app"
    autoDeploy: true
    healthCheckPath: "/health"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true